1주차
hyelin0111/minifullfillment pull request #1
Opened 2022-07-11 09:01 UTC by hyelin0111

Sku, Barcode, Center, Stock 도메인 추가

2022-07-11 09:42 UTC, vsh123 requested changes
멋져멋져 👍 
아래와 같은부분이 수정되면 좋을 것 같아요!

* 생성자를 호출하는 시점에 validation이 수행되면 좋을 것 같아요!
* setter를 전부 없애보면 좋을 것 같아요!!

2022-07-11 09:42 UTC, vsh123 commented on src/test/java/kvp/hhlin/minifullfillment/domain/BarcodeTest.java
> +    void Barcode생성() {
테스트 작성 👍

2022-07-11 09:42 UTC, vsh123 commented on src/main/java/kvp/hhlin/minifullfillment/domain/Center.java
> +    Center(String id, String name) {
public하게 만들지 않은 이유가 있나여?

2022-07-11 09:42 UTC, vsh123 commented on src/main/java/kvp/hhlin/minifullfillment/domain/Center.java
> +    private String status;
status는 Enum값을 그대로 가지고 있어도 괜찮을 것 같아요!!

```suggestion
    private CenterStatus status;
```

2022-07-11 09:42 UTC, vsh123 commented on src/main/java/kvp/hhlin/minifullfillment/domain/Barcode.java
> +
center에는 id가 있지만 여기에는 없는 이유가 궁금합니다!

2022-07-11 09:42 UTC, vsh123 commented on src/main/java/kvp/hhlin/minifullfillment/domain/Barcode.java
> +        this.setBarcode(barcode);
```suggestion
        this.barcode = barcode;
```

위와 같이 작성하면 setBarcode를 쓸 필요가 없을 것 같아요!

2022-07-11 09:42 UTC, vsh123 commented on src/main/java/kvp/hhlin/minifullfillment/domain/Barcode.java
> +    }
생성하는 시점에 isValidCode를 체크하면 더 좋을 것 같아!

```suggestion
    Barcode(String barcode) {
        isValidCode(barcode);
        this.barcode = barcode;
    }
```

2022-07-11 09:42 UTC, vsh123 commented on src/main/java/kvp/hhlin/minifullfillment/domain/Barcode.java
> +public class Barcode {
[이 글](https://stackoverflow.com/a/4695707)을 보구서 Barcode class내부의 layout을 정렬해보면 어떨까?

2022-07-11 09:42 UTC, vsh123 commented on src/main/java/kvp/hhlin/minifullfillment/domain/Sku.java
> +    private Set<Barcode> barcode;
barcode가 여러개들어갈 수 있다면 복수형으로 네이밍을해줘도 괜찮을 것 같은데, 어떻게 생각하시나요!

```suggestion
    private Set<Barcode> barcodes;
```

2022-07-11 09:42 UTC, vsh123 commented on src/main/java/kvp/hhlin/minifullfillment/domain/Sku.java
> +    private String status;
여기도 status를  enum으로 가지고 있어도 좋을 것 같아요!

2022-07-11 09:42 UTC, vsh123 commented on src/main/java/kvp/hhlin/minifullfillment/domain/Sku.java
> +    }
우리는 항상 위에서 아래로 읽는게 익숙하기 때문에, 해당 메서드들도 아래와 같이 순서를 바꿔주면 더 잘 읽히지 않을까?

```suggestion
    public void isValidName(String name) {
        if (!isValidLength(name) || isEmpty(name)) {
            throw new IllegalArgumentException("이름은 빈 값일 수 없고 최대 20자입니다.");
        }
    }
    
    private boolean isValidLength(String name) {
        return name.length() <= MAX_NAME_LENGTH;
    }

    private boolean isEmpty(String value) {
        return value.trim().length() == 0 || value.isEmpty() || value.isBlank();
    }
```

2022-07-11 09:42 UTC, vsh123 commented on src/main/java/kvp/hhlin/minifullfillment/domain/Sku.java
> +        return value.trim().length() == 0 || value.isEmpty() || value.isBlank();
java 11의 isBlank()활용 👍 
다만 isBlank는 isEmpty도 포함하고 있기 때문에 isBlank만 써줘도 충분할 것 같아요!

2022-07-12 14:17 UTC, mindock approved these changes
도메인 생성부터 테스트까지 좋아요~ 👍

2022-07-12 14:17 UTC, mindock commented on src/test/java/kvp/hhlin/minifullfillment/domain/BarcodeTest.java
> +        assertTrue(barcode.getBarcode().length() <= 20);
20자인 경우에는 에러가 발생하지 않는다는 것으로 테스트하면 좋을 것 같아요~

2022-07-12 14:17 UTC, mindock commented on src/main/java/kvp/hhlin/minifullfillment/domain/Stock.java
> +        this.quantity -= quantity;
여기서도 재고가 0보다 작지 않음을 검증하면 좋을 것 같아요~

2022-07-12 14:17 UTC, mindock commented on src/main/java/kvp/hhlin/minifullfillment/domain/Center.java
> +        this.status = CenterStatus.valueOf("READY").getStatus();
`CenterStatus.READY` 이렇게는 접근하지 못하나요?? valueOf 로만 가져올 수 있는건가요??

2022-07-18 03:01 UTC, vsh123 approved these changes
고생했어여!!!!!!!!!!!!!!!!!!

2022-07-19 14:27 UTC, merged