2주차
hyelin0111/minifullfillment pull request #2
Opened 2022-07-29 04:35 UTC by hyelin0111

Sku, Barcode, Center Repository/Service/Controller/Dto 추가

2022-07-29 17:09 UTC, vsh123 requested changes
고생했어요오~~~~~~~~~~~~~~~~~

2022-07-29 17:09 UTC, vsh123 commented on src/main/java/kvp/hhlin/minifullfillment/domain/Stock.java
> +    private Stock(String centerId, String skuCode) {
얘두 엔티티만들어주면 좋을 것 같아요!!

2022-07-29 17:09 UTC, vsh123 commented on src/main/java/kvp/hhlin/minifullfillment/repository/SkuRepository.java
> +
불필요한 공백은 제거하면 어떨까?!

2022-07-29 17:09 UTC, vsh123 commented on src/main/java/kvp/hhlin/minifullfillment/controller/SkuController.java
> +        return skuRepository.findAll();
[Transactional](https://tecoble.techcourse.co.kr/post/2021-05-25-transactional/) 어노테이션에 대해 알아보면 좋을 것 같아요!

2022-07-29 17:09 UTC, vsh123 commented on src/main/java/kvp/hhlin/minifullfillment/dto/BarcodCreateRequest.java
> +public class BarcodCreateRequest {
이런 애들을 dto라고 하는데 dto에 대해서도 알아보고 정리해보면 어떨까?
[참고](https://tecoble.techcourse.co.kr/post/2021-04-25-dto-layer-scope/)

2022-07-30 04:16 UTC, mindock approved these changes
이번에 JPA를 적용해봤군요~!! 좋아요 👍

2022-07-30 04:16 UTC, mindock commented on src/main/java/kvp/hhlin/minifullfillment/domain/Stock.java
> +    private Stock(String centerId, String skuCode) {
stock JPA 사용하도록 하는 건 다음주에 하나요??

2022-07-30 04:16 UTC, mindock commented on src/main/java/kvp/hhlin/minifullfillment/domain/Sku.java
> +    @JoinColumn(name = "sku_id")
@OneToMany를 사용할 때는 mappedBy를 주로 사용하는데, 혹시 JoinColumn 을 사용한 이유가 있나요??

2022-07-30 05:37 UTC, vsh123 commented on src/main/java/kvp/hhlin/minifullfillment/domain/Sku.java
> +    @JoinColumn(name = "sku_id")
요고는 내가 답변할 수 있을 것 같아여!!
단방향이여서 JoinColumn으루 했어용
[참고](https://jaegukim.github.io/posts/joincolumn-vs-mappedby-orm%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%A0%EB%95%8C-%EC%A3%BC%EC%9D%98%ED%95%A0%EC%A0%90/)

2022-08-03 11:06 UTC, hyelin0111 commented on src/main/java/kvp/hhlin/minifullfillment/domain/Stock.java
> +    private Stock(String centerId, String skuCode) {
[e33da85](https://github.com/hyelin0111/minifullfillment/pull/2/commits/e33da8536d4d6050dbdb871bcf49f03d4eaad6d7)

2022-08-03 11:06 UTC, merged